//! STUN Binding Request/Response helpers using the `stun-types` crate.
//!
//! Provides thin wrappers around `stun_types` to build Binding Requests and
//! parse XOR-MAPPED-ADDRESS from Binding Responses.

use std::net::SocketAddr;

use stun_types::attribute::XorMappedAddress;
use stun_types::message::{Message, MessageClass, BINDING};
use tracing::trace;

/// Build a STUN Binding Request as a serialized byte buffer.
///
/// The transaction ID is automatically generated by `stun-types`.
pub fn build_binding_request() -> Vec<u8> {
    Message::builder_request(BINDING).build()
}

/// Attempt to parse a STUN Binding Response and extract the public address.
///
/// Returns `Some(SocketAddr)` if the packet is a valid Binding Success Response
/// containing an XOR-MAPPED-ADDRESS attribute. Returns `None` for any other
/// message type, parse failure, or missing attribute.
pub fn parse_binding_response(data: &[u8]) -> Option<SocketAddr> {
    let msg = match Message::from_bytes(data) {
        Ok(msg) => msg,
        Err(e) => {
            trace!("STUN parse failed (likely not a STUN packet): {e}");
            return None;
        }
    };

    if !msg.has_class(MessageClass::Success) || !msg.has_method(BINDING) {
        trace!("STUN packet is not a Binding Success Response, ignoring");
        return None;
    }

    match msg.attribute::<XorMappedAddress>() {
        Ok(mapped) => {
            let addr = mapped.addr(msg.transaction_id());
            Some(addr)
        }
        Err(e) => {
            tracing::warn!("Failed to parse XOR-MAPPED-ADDRESS: {e}");
            None
        }
    }
}

/// Quick check: could this byte buffer be a STUN packet?
///
/// Per RFC 7983 multiplexing, STUN packets have first byte in 0x00..=0x03.
/// This allows fast rejection before attempting full parse.
#[inline]
pub fn could_be_stun(data: &[u8]) -> bool {
    matches!(data.first(), Some(0x00..=0x03))
}
